// app/page.tsx
import TestScriptBuilder from "@/components/test-script-builder";
import { Button } from "@/components/ui/button";
import Image from "next/image";

export default function Home() {
  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-6">FHIR TestScript Builder</h1>
      <TestScriptBuilder />
    </main>
  );
}

// app.vue
<template>
  <div class="min-h-screen bg-background p-4">
    <div class="container mx-auto">
      <header class="mb-6">
        <h1 class="text-2xl font-bold">FHIR TestScript Builder</h1>
        <p class="text-muted-foreground">Erstelle und bearbeite TestScript-Ressourcen</p>
      </header>
      
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <TestScriptForm />
        <TestScriptPreview />
      </div>
    </div>

    <Toaster />
  </div>
</template>
